services:
  todo-frontend:
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    image: hello-front-dev
    container_name: hello-front-dev
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api/
    volumes:
      - ./todo-frontend:/usr/src/app

  mongo:
    image: mongo
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
    - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    - ./todo-backend/mongo/data:/data/db
  redis:
    image: redis
    command: ['redis-server','--appendonly','yes']
    volumes:
      - ./todo-backend/redis_data:/data
  todo-backend:
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    image: hello-back-dev
    container_name: hello-back-dev
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://root:example@mongo:27017/the_database?authSource=admin
  nginx:
    image: nginx:1.29
    container_name: reverse-proxy
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo-frontend
      - todo-backend
